version: "0.1.0"
services: 
  web:
    build: .
    command: pylint --recursive=y /opt/service
    environment:
      - FLASK_APP=microblog.py
      - FLASK_ENV=development
      - TACKLE_ENVIROMENT=dev
    ports:
      - "8000:5000"
    volumes:
      - /Users/boyd.hemphill/code/tackle-python-flask-dev-env/:/opt/service