name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This job is now running on - ${{ runner.os }}"
      - run: echo "The name of branch is - ${{ github.ref }}"
      - run: echo "The name of repository is - ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "${{ github.workspace }}/requirements.txt"
        run: pip3 install pylint pytest radon>5.1
      - name: Linting
        run: pylint --recursive=y ${{ github.workspace }}
      - name: Tests
        if: success() || failure()
        run: pytest ${{ github.workspace }}/app/routes.py
      - run: echo "This job's status is ${{ job.status }}."
