name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This job is now running on - ${{ runner.os }}"
      - run: echo "The name of branch is - ${{ github.ref }}"
      - run: echo "The name of repository is - ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install linter
        run: pip3 install pylint
      - name: Linting
        run: pylint --recursive=y ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
